### ISSUE TITLE
OpenCV integration and licensing

### ISSUE THREAD

**Issue by catree** [tobycollins/IPPE#4]
I am considering about adding the IPPE method in OpenCV, to try to have a generic interface with:

- 2 solutions with IPPE flags and planar case
- 4 solutions with P3P and 3 points
- 1 solution otherwise
- possibility to have the reprojection error?

Will you agree with an integration of your method into OpenCV?

It seems that the IPPE license is the 4-Clause BSD License which is not compatible with the OpenCV 3-Clause BSD License. I guess that the added code would need to be relicensed to comply with the 3-Clause BSD License if you agree for an integration? But I am not an expert in software licensing.

Thanks.

**Comment by tobycollins** [comment]
Hi, thanks for your suggestion. Integration of IPPE into OpenCV is a great objective and I would certainly support it and make a license change. I agree that the generic interface is needed. I have also been thinking of this myself. I would say that for a generic interface, when we call OpenCV's solvePnP with a particular method, we want to return a list of pose solutions together with their respective reprojection errors. That's why I think it's best to return a vector of pose solutions.

It's not possible to always say in advance how many pose solutions should be returned. For example, for P3P there is no guarantee that 4 solutions will be returned (4 is the maximal number, but there can be between 0 and 4 real-valued solutions). By contrast, IPPE has an advantage that it guarantees 2 pose solutions.

It would also be good to have a mechanism to indicate whether the solution with lowest reprojection error is significantly better than the others, in which case we can assume the case has a unique solution. It is possible to do this using a [likelihood ratio test](https://en.wikipedia.org/wiki/Likelihood-ratio_test) threshold.

**Comment by catree** [comment]
Thanks for your input.
I will report here when a first implementation draft will be available.

**Comment by tobycollins** [comment]
Sure, looking forward to it!

**Comment by catree** [comment]
Thanks for your help!

**Comment by tobycollins** [comment]
Thank you for all your work to integrate it!
